# ---------- shortcut start ----------
# This code was auto-generated by `$ shortcut setup`.
# See `$ shortcut -- help` for more info.
function s() {
    if [ "$1" == "-a" ]; then
        shortcut add "$2" "$3"
    elif [ "$1" == "-r" ]; then
        shortcut remove "$2"
    elif [ "$1" == "-l" ]; then
        shortcut list
    elif [ "$1" == "-b" ]; then
        popd
    else
        pushd $(shortcut get "$1")
    fi 
    pwd
}
# ---------- shortcut end ----------
