# ---------- shortcut start ----------
# This code was auto-generated by `$ shortcut setup`.
# See `$ shortcut -- help` for more info.
function s {
    param (
        [Parameter(
            Position = 0,
            Mandatory = $true,
            HelpMessage="Enter <KEY> or one of the following commands: `"+`", `"-`", `"*`".")]
        [string]$p1,
        [Parameter(Position = 1)]
        [string]$p2,
        [Parameter(Position = 2)]
        [string]$p3
    )
    if ($p1 -eq "-a") {
        shortcut add $p2 $p3
    } elseif ($p1 -eq "-r") {
        shortcut remove $p2
    } elseif ($p1 -eq "-l") {
        shortcut list
    } elseif ($p1 -eq "-l") {
        Pop-Location
    } else {
        $dir = shortcut get $p1
        Push-Location "$dir"
    }
}
# ---------- shortcut end ----------
