# ---------- shortcut start ----------
# This code was auto-generated by `$ shortcut setup`.
# See `$ shortcut -- help` for more info.
function s {
    param (
        [Parameter(Position = 0, Mandatory = $true)] [string]$p1,
        [Parameter(Position = 1)] [string]$p2,
        [Parameter(Position = 2)] [string]$p3
    )
    if ($p1 -eq "+") {
        shortcut add $p2
    } elseif ($p1 -eq "-") {
        if ($p2) {
            shortcut remove $p2 $p3
        } else {
            Pop-Location
        }
    } elseif ($p1 -eq "*") {
        shortcut list
    } else {
        $dir = shortcut get $p1
        Push-Location "$dir"
    }
}
# ---------- shortcut end ----------
