:: This code was auto-generated by `$ shortcut setup`.
:: See `$ shortcut -- help` for more info.
@ECHO OFF
IF "%1"=="-a" (
    shortcut add "%~2" "%~3"
) ELSE IF "%1"=="-r" (
    shortcut remove "%~2"
) ELSE IF "%1"=="-l" (
    shortcut list
) ELSE IF "%1"=="-b" (
    POPD
) ELSE (
    FOR /F "usebackq delims=" %%G in (`shortcut get "%~1"`) DO (PUSHD "%%G")
)
