:: This code was auto-generated by `$ shortcut setup`.
:: See `$ shortcut -- help` for more info.
@ECHO OFF
IF "%1"=="+" (
    shortcut add "%~2" "%~3"
) ELSE IF "%1"=="-" (
    IF "%~2"=="" (
        POPD
    ) ELSE (
        shortcut remove "%~2"
    )
) ELSE IF "%1"=="*" (
    shortcut list
) ELSE (
    FOR /F "usebackq delims=" %%G in (`shortcut get "%~1"`) DO (PUSHD "%%G")
)
