# ---------- shortcut start ----------
# This code was auto-generated by `$ shortcut setup`.
# See `$ shortcut -- help` for more info.
SHORTCUT_PREV_DIR=""
s() {
    if [ "$1" = "-a" ]; then
        shortcut add "$2" "$3"
    elif [ "$1" = "-r" ]; then
        shortcut remove "$2"
    elif [ "$1" = "-l" ]; then
        shortcut list
    elif [ "$1" = "-b" ]; then
        _TMP="$SHORTCUT_PREV_DIR"
        if [ -n "$_TMP" ]; then
            SHORTCUT_PREV_DIR="$(pwd)"
            cd "$_TMP"
        else
            echo "There is no previous directory to cd to."
        fi 
    else
        SHORTCUT_PREV_DIR="$(pwd)"
        cd $(shortcut get "$1")
    fi 
}
# ---------- shortcut end ----------
