# ---------- shortcut start ---------- 
#
# This code was auto-generated by `$ shortcut setup`.
# See `$ shortcut -- help` for more info.
function s {
    param (
        [Parameter(Position = 0, Mandatory = $true)] [string]$p1,
        [Parameter(Position = 1)] [string]$p2,
        [Parameter(Position = 2)] [string]$p3
    )
    if ($p1 -eq "+") {
        Write-Output "[PS] Running: shortcut add `"$p2`""
        shortcut add $key
        Write-Output "[PS] shortcut add finished"
    } elseif ($p1 -eq "-") {
        if ($p2) {
            Write-Output "[PS] Running: shortcut remove `"$p2`" `"$p3`""
            shortcut remove $key $Value
            Write-Output "[PS] shortcut remove finished"
        } else {
            Write-Output "[PS] Running: Pop-Location"
            Pop-Location
            Write-Output "[PS] Pop-Location finished"
        }
    } elseif ($p1 -eq "*") {
        Write-Output "[PS] Running: shortcut list"
        shortcut list
        Write-Output "[PS] shortcut list finished"
    } elseif ($p1 -eq "dl") {
        Write-Output "[PS] Using shortcut: `"$p1`""
        Push-Location "C:\Users\nique\Downloads"
    } else {
        Write-Output "[PS] Running: Push-Location `"$p1`""
        Push-Location "$p1"
        Write-Output "[PS] Push-Location finished"
    }
}
# ---------- shortcut end ---------- 
